//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraktikaProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Task
    {
        [DisplayName("Task description:")]
        public int TaskId { get; set; }
        public string TaskDescr { get; set; }
        [NotMapped]
        public List<Task> TaskCollection { get; set; }
    }
}
