//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraktikaProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int userID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string username { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string password { get; set; }
        public bool isAdmin { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
